version: '3'

services:
    part5:
        build: ../part5/
        container_name: temp
    proxy-nginx:
        image: nginx
        container_name: proxy
        ports:
            - 80:8080
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
